[package]
name = "herald-infra"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints.clippy]
too_many_arguments = "allow"

[dependencies]
herald-domain = { path = "../domain" }
herald-entity = { path = "../entity" }
herald-infra-stripe = { path = "../infra-stripe" }
herald-infra-creem = { path = "../infra-creem" }
herald-infra-iap = { path = "../infra-iap" }
herald-infra-wechatpay = { path = "../infra-wechatpay" }
sea-orm = { workspace = true }
sqlx = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
oauth2 = { workspace = true }
jsonwebtoken = { workspace = true }
base64 = { workspace = true }
urlencoding = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
ldap3 = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
rustls-native-certs = { workspace = true }
ironpress = "1"

[dev-dependencies]
herald-test-db = { path = "../test-db" }
futures = { workspace = true }
tokio = { workspace = true }
