[package]
name = "herald-api-ext"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
hex = { workspace = true }
redis = { workspace = true }
sha2 = { workspace = true }
herald-api-base = { path = "../api-base" }
herald-core = { path = "../core" }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
validator = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
sea-orm = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
