// Herald API Admin Module
// Admin handlers, role definitions, permission management

pub mod admin;
pub mod api_keys;
pub mod audit;
pub mod client_apps;
pub mod dashboard;
pub mod permission;
pub mod role_definitions;

// Re-export router functions for use by the main api crate
pub use admin::admin_router_with_middleware;

/// OpenAPI specification for admin module
#[derive(utoipa::OpenApi)]
#[openapi(
    paths(
        crate::admin::admin_users::list_users,
        crate::admin::admin_users::create_user,
        crate::admin::admin_users::get_user,
        crate::admin::admin_users::update_user,
        crate::admin::admin_users::delete_user,
        crate::admin::admin_users::reset_user_password,
        crate::admin::admin_users::sessions::list_user_sessions,
        crate::admin::admin_users::sessions::revoke_user_session,
        crate::admin::admin_users::sessions::revoke_all_user_sessions,
        crate::admin::admin_users::roles::get_user_roles,
        crate::admin::admin_users::roles::update_user_roles,
        crate::admin::admin_users::permissions::get_user_permissions,
        crate::admin::admin_users::permissions::assign_user_permission,
        crate::admin::admin_users::permissions::remove_user_permission,
        crate::admin::admin_users::permissions::get_effective_permissions,
        crate::admin::permission::check_permission,
        crate::permission::role_policies::get_role_policies,
        crate::permission::role_policies::add_policy_to_role,
        crate::permission::role_policies::remove_policy_from_role,
        crate::permission::user_roles::get_user_roles,
        crate::permission::user_roles::assign_roles_to_user,
        crate::permission::user_roles::remove_role_from_user,
        crate::role_definitions::list_roles,
        crate::role_definitions::create_role,
        crate::role_definitions::get_role,
        crate::role_definitions::update_role,
        crate::role_definitions::delete_role,
        crate::role_definitions::assign_permission_to_role,
        crate::role_definitions::get_role_permissions,
        crate::role_definitions::remove_permission_from_role,
        crate::admin::permission_definitions::list_permission_definitions,
        crate::admin::permission_definitions::create_permission_definition,
        crate::admin::permission_definitions::get_permission_definition,
        crate::admin::permission_definitions::update_permission_definition,
        crate::admin::permission_definitions::delete_permission_definition,
        crate::audit::list::list_audit_events,
        crate::audit::detail::get_audit_event,
        crate::dashboard::get_dashboard_stats,
        crate::client_apps::list::list_client_apps,
        crate::client_apps::create::create_client_app,
        crate::client_apps::get::get_client_app,
        crate::client_apps::update::update_client_app,
        crate::client_apps::delete::delete_client_app,
        crate::api_keys::list::list_api_keys,
        crate::api_keys::create::create_api_key,
        crate::api_keys::get::get_api_key,
        crate::api_keys::update::update_api_key,
        crate::api_keys::delete::delete_api_key,
        crate::api_keys::rotate::rotate_api_key,
        crate::api_keys::roles::get_api_key_roles,
        crate::api_keys::roles::update_api_key_roles,
    ),
    components(schemas(
        crate::role_definitions::types::RoleCreateRequest,
        crate::role_definitions::types::RoleUpdateRequest,
        crate::role_definitions::types::RoleResponse,
        crate::role_definitions::types::AssignPermissionRequest,
        crate::role_definitions::types::PermissionResponse,
        crate::admin::permission_definitions::types::PermissionCreateRequest,
        crate::admin::permission_definitions::types::PermissionUpdateRequest,
        crate::admin::permission_definitions::types::PermissionResponse,
        crate::admin::admin_users::types::UserRoleDetail,
        crate::admin::admin_users::types::UserRolesResponse,
        crate::admin::admin_users::types::UpdateUserRolesRequest,
        crate::admin::admin_users::types::UserPermission,
        crate::admin::admin_users::types::UserPermissionsResponse,
        crate::admin::admin_users::types::DirectPermissionRequest,
        crate::admin::admin_users::types::EffectivePermission,
        crate::admin::admin_users::types::EffectivePermissionsResponse,
        crate::permission::role_policies::PolicyResponse,
        crate::permission::role_policies::RolePoliciesResponse,
        crate::permission::role_policies::AddPolicyRequest,
        crate::permission::user_roles::PermissionRoleResponse,
        crate::permission::user_roles::PermissionUserRolesResponse,
        crate::permission::user_roles::AssignRolesRequest,
        crate::audit::types::AuditEventResponse,
        crate::audit::types::AuditEventDetailResponse,
        crate::audit::types::AuditEventListResponse,
        crate::dashboard::DashboardStatsResponse,
        crate::dashboard::UserStatsResponse,
        crate::dashboard::AuthTrendPointResponse,
        crate::client_apps::types::ClientAppCreateRequest,
        crate::client_apps::types::ClientAppUpdateRequest,
        crate::client_apps::types::ClientAppItem,
        crate::api_keys::types::CreateApiKeyRequest,
        crate::api_keys::types::CreateApiKeyResponse,
        crate::api_keys::types::ApiKeyListItem,
        crate::api_keys::types::UpdateApiKeyRequest,
        crate::api_keys::types::UpdateApiKeyRolesRequest,
        crate::api_keys::types::ApiKeyRolesResponse,
        crate::api_keys::types::ApiKeyRoleDetail,
        herald_api_base::application::http::common::pagination::PaginationMeta,
        herald_api_base::application::http::server::api_entities::PageResponse<crate::client_apps::types::ClientAppItem>,
        herald_api_base::application::http::server::api_entities::PageResponse<crate::api_keys::types::ApiKeyListItem>,
    ))
)]
pub struct ApiDoc;
