[package]
name = "herald-api-auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
herald-api-base = { path = "../api-base" }
herald-core = { path = "../core" }
axum = { workspace = true }
axum-valid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
validator = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
redis = { workspace = true }
sqlx = { workspace = true }
bcrypt = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
url = { workspace = true }

[dev-dependencies]
